apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-api-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath:
    path: /home/go-api-pv
