apiVersion: v1
kind: Secret
metadata:
  name: go-api-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=        # admin
  DB_PASSWORD: c3VwZXJzZWNyZXQ= # supersecret
  # MONGODB_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L3RvZG8= # mongodb://mongo:27017/todo
  # echo -n 'mongodb://mongo:27017/todo' | base64
  # MONGODB_URI: bW9uZ29kYjovL2hvc3QuZG9ja2VyLmludGVybmFsOjI3MDE3
  # MONGODB_URI: bW9uZ29kYjovLzE3Mi4xNy4wLjE6MjcwMTc=
  MONGODB_URI: bW9uZ29kYjovL2RiLXNlcnZpY2U6MjcwMTcvdG9kb3MK
